name: nl-ddm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - numpy
  - pathos
  - scipy
  - seaborn
  - pip:
    - paranoid-scientist==0.2.2
    - pyddm==0.5.2
    - zipfile38==0.0.3
